### ISSUE TITLE
Add support for EL7

### ISSUE THREAD

**Issue by lorengordon** [plus3it/splunkforwarder-formula#4]
Currently, the formula fails on EL7 due to the `iptables` states:

```
----------
          ID: Allow Splunk Mgmt Outbound Port 8089
    Function: iptables.append
      Result: False
     Comment: State 'iptables.append' was not found in SLS 'splunkforwarder.elx'
              Reason: 'iptables' __virtual__ returned False
     Changes:   
----------
          ID: Allow Splunk Mgmt Outbound Port 9997
    Function: iptables.append
      Result: False
     Comment: State 'iptables.append' was not found in SLS 'splunkforwarder.elx'
              Reason: 'iptables' __virtual__ returned False
     Changes:  
```
